# Generated by Django 6.0.1 on 2026-03-17 22:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_community_is_active_flag_count'),
        ('community_abuse_report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunityReport',
            new_name='CommunityAbuseReport',
        ),
        migrations.AlterModelOptions(
            name='communityabusereport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Community Abuse Report', 'verbose_name_plural': 'Community Abuse Reports'},
        ),
        migrations.AlterModelTable(
            name='communityabusereport',
            table='CommunityAbuseReport',
        ),
    ]
