# Generated by Django 6.0.1 on 2026-01-28 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title/question of the poll', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description or additional context for the poll', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this poll is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(help_text='Community this poll belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='community.community')),
                ('payment_plans', models.ManyToManyField(blank=True, help_text='Payment plans that have access to this poll. Owners, co-owners, and moderators have access regardless of payment plan.', related_name='polls', to='community.paymentplan')),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
                'db_table': 'Poll',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Text of the poll option', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Order/position of this option in the poll')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(help_text='Poll this option belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='community_polls.poll')),
            ],
            options={
                'verbose_name': 'Poll Option',
                'verbose_name_plural': 'Poll Options',
                'db_table': 'PollOption',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(help_text='Poll option that was voted for', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community_polls.polloption')),
                ('poll', models.ForeignKey(help_text='Poll this vote belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community_polls.poll')),
                ('user', models.ForeignKey(help_text='User who cast the vote', on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poll Vote',
                'verbose_name_plural': 'Poll Votes',
                'db_table': 'PollVote',
                'ordering': ['-created_at'],
                'unique_together': {('poll', 'user')},
            },
        ),
    ]
