# Generated by Django 6.0.1 on 2026-01-28 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(help_text='Unique job identifier (GUID/UUID)', max_length=36, unique=True)),
                ('meta_data', models.TextField(help_text='JSON string containing job metadata (title, description, communityId, totalNumberOfQuestions, totalNumberOfMultipleChoice, totalNumberOfSingleChoice, isTimed, hasAttemptLimit, maxAttempts)')),
                ('file_url', models.CharField(help_text='Path to file in storage bucket containing notes for quiz generation', max_length=500)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', help_text='Status of the quiz generation job', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job was completed', null=True)),
            ],
            options={
                'verbose_name': 'Quiz Generation Job',
                'verbose_name_plural': 'Quiz Generation Jobs',
                'db_table': 'QuizGenerationJob',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the quiz', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the quiz', null=True)),
                ('quiz_data', models.TextField(help_text='JSON string containing quiz questions and structure')),
                ('is_timed', models.BooleanField(default=False, help_text='Whether this quiz is timed (has a time limit)')),
                ('has_attempt_limit', models.BooleanField(default=False, help_text='Whether this quiz has a limit on the number of attempts')),
                ('max_attempts', models.PositiveIntegerField(blank=True, help_text='Maximum number of attempts allowed if has_attempt_limit is True', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(help_text='Community this quiz belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='community.community')),
                ('payment_plans', models.ManyToManyField(blank=True, help_text='Payment plans that have access to this quiz. Owners and co-owners have access regardless of payment plan.', related_name='quizzes', to='community.paymentplan')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'Quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_data', models.TextField(help_text='JSON string containing submission data with questions answered, correct/incorrect answers')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Score achieved (percentage)', max_digits=5, null=True)),
                ('total_questions', models.IntegerField(help_text='Total number of questions in the quiz')),
                ('correct_answers', models.IntegerField(default=0, help_text='Number of correct answers')),
                ('incorrect_answers', models.IntegerField(default=0, help_text='Number of incorrect answers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(help_text='Quiz that was submitted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='community_quiz.quiz')),
                ('user', models.ForeignKey(help_text='User who submitted the quiz', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Submission',
                'verbose_name_plural': 'Quiz Submissions',
                'db_table': 'QuizSubmission',
                'ordering': ['-created_at'],
            },
        ),
    ]
