# Generated by Django 6.0.1 on 2026-01-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the blog post', max_length=255)),
                ('slug', models.SlugField(db_index=True, help_text='URL-friendly identifier (auto-generated from title, unique per community)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Short description/summary of the blog post', null=True)),
                ('blog_message', models.TextField(help_text='Content of the blog post')),
                ('image_url', models.URLField(blank=True, help_text='URL of the blog post image', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(help_text='Community this blog post belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='community.community')),
                ('writer', models.ForeignKey(help_text='User who wrote this blog post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Blog Post',
                'verbose_name_plural': 'Community Blog Posts',
                'db_table': 'CommunityBlogPost',
                'ordering': ['-created_at'],
                'unique_together': {('community', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CommunityBlogPostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Reply message content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community_blog_post', models.ForeignKey(help_text='Blog post this reply belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community_blog.communityblogpost')),
                ('user', models.ForeignKey(help_text='User who wrote this reply (no community membership required)', on_delete=django.db.models.deletion.CASCADE, related_name='community_blog_post_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Blog Post Reply',
                'verbose_name_plural': 'Community Blog Post Replies',
                'db_table': 'CommunityBlogPostReply',
                'ordering': ['created_at'],
            },
        ),
    ]
