# Generated by Django 6.0.1 on 2026-01-28 18:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.SlugField(help_text='Unique URL-friendly identifier. Only letters, numbers, hyphens (-) and underscores (_) allowed.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug_username', message='May only contain letters, numbers, hyphens (-) and underscores (_).', regex='^[a-zA-Z0-9_-]+$')])),
                ('summary', models.CharField(blank=True, help_text='Short summary of the community', max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('public_notes', models.TextField(blank=True, help_text='Public notes visible to all community members and visitors', null=True)),
                ('category', models.CharField(blank=True, help_text='Community category', max_length=100, null=True)),
                ('is_open', models.BooleanField(default=True, help_text='If true, users can join without approval. If false, users become applicants needing approval.')),
                ('restrict_posting_to_owners_moderators', models.BooleanField(default=False, help_text='If true, only owners and moderators can post on the community forum. If false, all members can post.')),
                ('use_logo_only', models.BooleanField(default=False, help_text='If true, the community should be represented only by its logo/avatar without showing the name text. If false, display both logo and name. This is for frontend display purposes.')),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='communities', to='shared.tag')),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
                'db_table': 'Community',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('co_owner', 'Co-Owner'), ('moderator', 'Moderator'), ('contributor', 'Contributor'), ('member', 'Member'), ('applicant', 'Applicant')], default='applicant', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False, help_text='Whether the user is blocked from the community')),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this membership (for applicants)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_memberships', to=settings.AUTH_USER_MODEL)),
                ('blocked_by', models.ForeignKey(blank=True, help_text='User who blocked this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_memberships', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_members', to='community.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Member',
                'verbose_name_plural': 'Community Members',
                'db_table': 'CommunityMember',
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'community')},
            },
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='communities', through='community.CommunityMember', through_fields=('community', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the payment plan (e.g., "Standard", "Premium", "Enterprise")', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this plan offers', null=True)),
                ('fee', models.DecimalField(decimal_places=2, help_text='Subscription fee for this plan', max_digits=10)),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether this payment plan is recurring (subscription-based)')),
                ('is_free', models.BooleanField(default=False, help_text='Whether this plan is free. If True, fee will be automatically set to 0 and is_recurring will be False.')),
                ('offerings', models.JSONField(blank=True, default=dict, help_text='JSON field to store plan offerings/features')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently active and available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='community.community')),
            ],
            options={
                'verbose_name': 'Payment Plan',
                'verbose_name_plural': 'Payment Plans',
                'db_table': 'PaymentPlan',
                'ordering': ['created_at'],
                'unique_together': {('community', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CommunityFeaturedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], help_text='Type of featured content: "image" or "video"', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Title for the featured content', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the featured content', null=True)),
                ('image_url', models.URLField(blank=True, help_text='URL of the featured image (if content_type is image)', null=True)),
                ('video_url', models.URLField(blank=True, help_text='Video URL - can be uploaded video file URL (MinIO) or external video URL (YouTube, Vimeo, etc.) (if content_type is video)', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this featured content is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_contents', to='community.community')),
            ],
            options={
                'verbose_name': 'Community Featured Content',
                'verbose_name_plural': 'Community Featured Contents',
                'db_table': 'CommunityFeaturedContent',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['community', 'is_active'], name='CommunityFe_communi_7e83b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunityLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Like',
                'verbose_name_plural': 'Community Likes',
                'db_table': 'CommunityLike',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'community')},
            },
        ),
        migrations.CreateModel(
            name='UserPaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the subscription expires (null for lifetime)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subscription is currently active')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='community.community')),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='community.paymentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Payment Plan',
                'verbose_name_plural': 'User Payment Plans',
                'db_table': 'UserPaymentPlan',
                'ordering': ['-subscribed_at'],
                'unique_together': {('user', 'community')},
            },
        ),
    ]
