# Generated by Django 6.0.1 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityfeaturedcontent',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this featured content is public (visible to non-members)'),
        ),
    ]
