# Generated by Django 6.0.1 on 2026-01-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communityfeaturedcontent_is_public'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityFeaturedContent',
        ),
    ]
