# Generated by Django 6.0.1 on 2026-01-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_delete_communityfeaturedcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityBadgeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code within the community (e.g. first_post, posts_5, post_likes_100)', max_length=64)),
                ('name', models.CharField(help_text='Display name of the badge', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Short description of how to earn this badge', null=True)),
                ('icon_url', models.URLField(blank=True, help_text='URL of the badge icon image (optional)', null=True)),
                ('criteria', models.JSONField(blank=True, default=dict, help_text='Optional criteria (e.g. {"min_posts": 5})')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(help_text='Community this badge belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='badge_definitions', to='community.community')),
            ],
            options={
                'verbose_name': 'Community Badge Definition',
                'verbose_name_plural': 'Community Badge Definitions',
                'db_table': 'CommunityBadgeDefinition',
                'ordering': ['community', 'code'],
                'unique_together': {('community', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CommunityMemberBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('community_badge', models.ForeignKey(help_text='The community badge that was awarded', on_delete=django.db.models.deletion.CASCADE, related_name='member_badges', to='community.communitybadgedefinition')),
                ('community_member', models.ForeignKey(help_text='Community member who was awarded this badge', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='community.communitymember')),
            ],
            options={
                'verbose_name': 'Community Member Badge',
                'verbose_name_plural': 'Community Member Badges',
                'db_table': 'CommunityMemberBadge',
                'ordering': ['-awarded_at'],
                'unique_together': {('community_member', 'community_badge')},
            },
        ),
    ]
