# Generated by Django 6.0.1 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_communitybadgedefinition_communitymemberbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='points',
            field=models.PositiveBigIntegerField(default=0, help_text='Cumulative points for community leaderboard'),
        ),
    ]
