# Generated by Django 6.0.1 on 2026-03-14 15:17

import app_models.community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_communityview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymember',
            name='leaderboard_year',
            field=models.PositiveSmallIntegerField(default=app_models.community.models._current_year, help_text='Year this leaderboard period applies to; points reset when year changes.'),
        ),
    ]
