# Generated by Django 6.0.1 on 2026-03-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_communitymember_leaderboard_year'),
        ('community', '0008_communityview_referrer_and_location'),
    ]

    operations = [
    ]
