# Generated by Django 6.0.1 on 2026-03-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_rename_payment_plan_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitygroup',
            options={'ordering': ['created_at'], 'verbose_name': 'Community Group', 'verbose_name_plural': 'Community Groups'},
        ),
        migrations.AlterModelOptions(
            name='communitygroupaccess',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Community Group Access', 'verbose_name_plural': 'Community Group Access'},
        ),
        migrations.AlterField(
            model_name='communitygroup',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what this tier offers', null=True),
        ),
        migrations.AlterField(
            model_name='communitygroup',
            name='fee',
            field=models.DecimalField(decimal_places=2, help_text='Subscription fee for this tier', max_digits=10),
        ),
        migrations.AlterField(
            model_name='communitygroup',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this tier is currently active and available'),
        ),
        migrations.AlterField(
            model_name='communitygroup',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Whether this tier is free. If True, fee will be automatically set to 0 and is_recurring will be False.'),
        ),
        migrations.AlterField(
            model_name='communitygroup',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this tier is recurring (subscription-based)'),
        ),
        migrations.AlterField(
            model_name='communitygroup',
            name='name',
            field=models.CharField(help_text='Name of the group tier (e.g., "Standard", "Premium", "Enterprise")', max_length=255),
        ),
        migrations.AlterField(
            model_name='communitygroup',
            name='offerings',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field to store tier offerings/features'),
        ),
    ]
