# Generated by Django 6.0.1 on 2026-04-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_communitygroup_is_closed_communitygroupjoinrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communitygroupjoinrequest',
            new_name='CommunityGr_communi_639875_idx',
            old_name='cgjoinreq_grp_status_idx',
        ),
        migrations.RenameIndex(
            model_name='communitygroupjoinrequest',
            new_name='CommunityGr_user_id_d60a75_idx',
            old_name='cgjoinreq_user_grp_idx',
        ),
    ]
