# Generated by Django 6.0.1 on 2026-05-08 15:05

from django.db import migrations, models


def backfill_billing_period_from_legacy_flags(apps, schema_editor):
    CommunityGroup = apps.get_model('community', 'CommunityGroup')
    for group in CommunityGroup.objects.all().iterator():
        if group.is_lifetime:
            period = 'lifetime'
        elif group.is_yearly:
            period = 'yearly'
        else:
            period = 'monthly'
        CommunityGroup.objects.filter(pk=group.pk).update(billing_period=period)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('community', '0022_rename_cgjoinreq_grp_status_idx_communitygr_communi_639875_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitygroup',
            name='billing_period',
            field=models.CharField(
                choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime'), ('custom', 'Custom')],
                default='monthly',
                help_text='Billing cadence for paid tiers: monthly, yearly, lifetime, or custom fixed date range.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='custom_period_end_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Fixed access window end for custom billing period tiers.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='custom_period_start_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Fixed access window start for custom billing period tiers.',
                null=True,
            ),
        ),
        migrations.RunPython(backfill_billing_period_from_legacy_flags, noop_reverse),
    ]
