# Generated by Django 6.0.1 on 2026-05-08 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('community', '0023_communitygroup_billing_period_custom_window'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitygroup',
            name='is_lifetime',
        ),
        migrations.RemoveField(
            model_name='communitygroup',
            name='is_monthly',
        ),
        migrations.RemoveField(
            model_name='communitygroup',
            name='is_yearly',
        ),
    ]
