# Generated by Django 6.0.1 on 2026-07-31 21:36

import app_models.community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0027_featuredcommunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymember',
            name='leaderboard_year',
            field=models.PositiveSmallIntegerField(default=app_models.community.models._current_year, help_text='Deprecated: unused for leaderboard resets; cumulative points use points only.'),
        ),
    ]
