# Generated by Django 6.0.1 on 2026-08-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0028_alter_communitymember_leaderboard_year'),
        ('community', '0028_alter_featuredcommunity_featured_image_url'),
    ]

    operations = [
    ]
