# Generated by Django 6.0.1 on 2026-08-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0029_merge_20260802_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='bunny_collection_id',
            field=models.CharField(blank=True, help_text='Bunny Stream collection GUID for communities/{id}', max_length=36, null=True),
        ),
    ]
