# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0030_community_bunny_collection_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('share_id', models.CharField(db_index=True, help_text='Unguessable public token used in the fill URL', max_length=32, unique=True)),
                ('audience', models.CharField(choices=[('members', 'Community members'), ('signed_in', 'Signed-in users'), ('anyone', 'Anyone with the link')], default='members', max_length=16)),
                ('is_open', models.BooleanField(default=True)),
                ('one_response_per_user', models.BooleanField(default=True)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(help_text='Community this form belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='community.community')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_community_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community form',
                'verbose_name_plural': 'Community forms',
                'db_table': 'CommunityForm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_snapshot', models.JSONField(default=dict)),
                ('answers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='community.community')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='community_forms.communityform')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_form_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community form response',
                'verbose_name_plural': 'Community form responses',
                'db_table': 'CommunityFormResponse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='communityform',
            index=models.Index(fields=['community', '-created_at'], name='cform_community_created_idx'),
        ),
        migrations.AddIndex(
            model_name='communityformresponse',
            index=models.Index(fields=['form', '-created_at'], name='cform_resp_form_created_idx'),
        ),
        migrations.AddIndex(
            model_name='communityformresponse',
            index=models.Index(fields=['community', '-created_at'], name='cform_resp_comm_created_idx'),
        ),
    ]
