# Generated by Django 6.0.1 on 2026-08-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_usage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageusage',
            name='file_path',
            field=models.CharField(help_text='Object storage key', max_length=500),
        ),
    ]
