# Generated by Django 6.0.1 on 2026-01-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional short name for the wheel', max_length=255, null=True)),
                ('request_message', models.TextField(help_text='The instruction (e.g. pay 200$, send a gift)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open_for_join', 'Open for Join'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('mode', models.CharField(choices=[('chain', 'Chain (sequential one-to-next)'), ('collective', 'Collective support (all-for-one rotation)')], default='chain', help_text='Wheel mode: chain (each member acts for the next) or collective (all act for one, then rotate)', max_length=20)),
                ('auto_approve_link_joins', models.BooleanField(default=False, help_text='If true (open wheel), users who join via link become participants automatically. If false (closed wheel), joins via link require approval.')),
                ('max_favor_duration_days', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum time a participant has to fulfil a wheel favour (in days, decimal allowed, e.g. 0.2)', max_digits=5, null=True)),
                ('max_members', models.PositiveIntegerField(blank=True, help_text='Optional max participants when joining via link', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(help_text='Community this wheel belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='wheels', to='community.community')),
                ('created_by', models.ForeignKey(help_text='Owner or moderator who created the wheel', on_delete=django.db.models.deletion.CASCADE, related_name='created_wheels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wheel',
                'verbose_name_plural': 'Wheels',
                'db_table': 'Wheel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WheelJoinLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Unique token for the join URL', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_joins', models.PositiveIntegerField(blank=True, help_text='Optional limit on number of joins', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_wheel_join_links', to=settings.AUTH_USER_MODEL)),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_links', to='community_wheel.wheel')),
            ],
            options={
                'verbose_name': 'Wheel Join Link',
                'verbose_name_plural': 'Wheel Join Links',
                'db_table': 'WheelJoinLink',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WheelParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Position in sequence (1 = first, 2 = second, ...)')),
                ('preference_message', models.TextField(blank=True, help_text='Member reference info (e.g. account number) for the person doing the request for them', null=True)),
                ('join_remark', models.CharField(blank=True, help_text='API-set text describing how they joined (e.g. "added by owner", "joined via link")', max_length=255, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Participant approval status (e.g. pending until they accept / are approved)', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_wheel_joins', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_participations', to=settings.AUTH_USER_MODEL)),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='community_wheel.wheel')),
            ],
            options={
                'verbose_name': 'Wheel Participant',
                'verbose_name_plural': 'Wheel Participants',
                'db_table': 'WheelParticipant',
                'ordering': ['wheel', 'order'],
                'unique_together': {('wheel', 'user'), ('wheel', 'order')},
            },
        ),
        migrations.CreateModel(
            name='WheelHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('action_done', 'Action Done'), ('acknowledged', 'Acknowledged')], db_index=True, default='pending', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Optional evidence note from the giver', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, help_text='User (anyone in the wheel) who acknowledged this handoff', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wheel_handoff_acknowledgements', to=settings.AUTH_USER_MODEL)),
                ('from_participant', models.ForeignKey(help_text='Participant who does the request', on_delete=django.db.models.deletion.CASCADE, related_name='handoffs_given', to='community_wheel.wheelparticipant')),
                ('to_participant', models.ForeignKey(help_text='Participant who receives', on_delete=django.db.models.deletion.CASCADE, related_name='handoffs_received', to='community_wheel.wheelparticipant')),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='community_wheel.wheel')),
            ],
            options={
                'verbose_name': 'Wheel Handoff',
                'verbose_name_plural': 'Wheel Handoffs',
                'db_table': 'WheelHandoff',
                'ordering': ['wheel', 'from_participant__order'],
                'unique_together': {('wheel', 'from_participant')},
            },
        ),
        migrations.CreateModel(
            name='WheelHandoffAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(help_text='URL of the attached file')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wheel_handoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='community_wheel.wheelhandoff')),
            ],
            options={
                'verbose_name': 'Wheel Handoff Attachment',
                'verbose_name_plural': 'Wheel Handoff Attachments',
                'db_table': 'WheelHandoffAttachment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WheelJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_wheel_join_requests', to=settings.AUTH_USER_MODEL)),
                ('join_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='community_wheel.wheeljoinlink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_join_requests', to=settings.AUTH_USER_MODEL)),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='community_wheel.wheel')),
            ],
            options={
                'verbose_name': 'Wheel Join Request',
                'verbose_name_plural': 'Wheel Join Requests',
                'db_table': 'WheelJoinRequest',
                'ordering': ['-created_at'],
                'unique_together': {('wheel', 'user')},
            },
        ),
    ]
