# Generated by Django 6.0.1 on 2026-01-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_wheel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheel',
            name='auto_approve_link_joins',
        ),
        migrations.DeleteModel(
            name='WheelJoinRequest',
        ),
        migrations.DeleteModel(
            name='WheelJoinLink',
        ),
    ]

