# Generated by Django 6.0.1 on 2026-01-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_wheel', '0002_remove_join_link_and_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheelparticipant',
            name='join_remark',
        ),
    ]

