# Generated by Django 6.0.1 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_wheel', '0003_remove_join_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes for the wheel', null=True),
        ),
    ]
