# Generated by Django 6.0.1 on 2026-01-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_wheel', '0004_wheel_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wheel',
            old_name='request_message',
            new_name='description',
        ),
    ]
