# Generated by Django 6.0.1 on 2026-01-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_wheel', '0005_rename_request_message_to_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wheel',
            old_name='notes',
            new_name='message',
        ),
    ]
