# Generated by Django 6.0.1 on 2026-02-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_wheel', '0006_rename_notes_to_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='description',
            field=models.TextField(help_text='The instruction or description (e.g. pay 200$, send a gift)'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message for the wheel', null=True),
        ),
    ]
