# Generated by Django 6.0.1 on 2026-02-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_wheel', '0008_ajo_round_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='round_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Length of each recipient’s round in days (e.g. 30). Deadline to pay = end of their round.', null=True),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the wheel/Ajo was started. First recipient’s round starts on this date.', null=True),
        ),
        migrations.AlterField(
            model_name='wheelparticipant',
            name='round_received_at',
            field=models.DateTimeField(blank=True, help_text='When this participant received everyone’s contribution (their round done). Next person’s round starts on this date.', null=True),
        ),
    ]
