# Generated by Django 6.0.1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_wheel', '0009_alter_wheel_round_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wheelhandoff',
            unique_together={('wheel', 'from_participant', 'to_participant')},
        ),
    ]
