# Generated by Django 6.0.1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_wheel', '0010_alter_wheelhandoff_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheel',
            name='mode',
        ),
    ]
