# Generated by Django 6.0.1

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Star rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('message', models.TextField(blank=True, help_text='Optional feedback message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(help_text='Community this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='community.community')),
                ('user', models.ForeignKey(help_text='User who left the feedback', on_delete=django.db.models.deletion.CASCADE, related_name='community_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Feedback',
                'verbose_name_plural': 'Community Feedbacks',
                'db_table': 'CommunityFeedback',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'community')},
            },
        ),
    ]
