# Generated by Django 6.0.1 on 2026-02-08 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communityfeaturedcontent_is_public'),
        ('community_feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='communityfeedback',
            index=models.Index(fields=['community'], name='CommunityFe_communi_759fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='communityfeedback',
            index=models.Index(fields=['user', 'community'], name='CommunityFe_user_id_68067b_idx'),
        ),
    ]
