# Generated by Django 6.0.1 on 2026-04-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_payments', '0005_paymentcheckoutsession'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentcheckoutsession',
            new_name='PaymentChec_user_id_3cb72e_idx',
            old_name='PaymentCheck_user_stat_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentcheckoutsession',
            new_name='PaymentChec_status_30faf0_idx',
            old_name='PaymentCheck_stat_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentcheckoutsession',
            new_name='PaymentChec_session_c79b33_idx',
            old_name='PaymentCheck_kind_stat_idx',
        ),
    ]
