# Generated by Django 6.0.1 on 2026-04-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_payments', '0007_event_registration_subjects'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='PaymentTran_event_r_9ed163_idx',
            old_name='PaymentTran_event_r_6194a6_idx',
        ),
    ]
