# Generated by Django 6.0.1 on 2026-01-29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Slug-like name (letters, numbers, hyphens, underscores). Used for URL/folder identifier.', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_slug_username', message='May only contain letters, numbers, hyphens (-) and underscores (_).', regex='^[a-zA-Z0-9_-]+$')])),
                ('friendly_name', models.CharField(help_text='Display name for the resource (folder name shown on frontend)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the resource', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(help_text='Community this resource belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='community.community')),
                ('payment_plans', models.ManyToManyField(blank=True, help_text='Payment plans that have access to this resource. Zero or many.', related_name='resources', to='community.paymentplan')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'db_table': 'Resource',
                'ordering': ['-created_at'],
                'unique_together': {('community', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ResourceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(help_text='Type of file (e.g. video, document, pdf, image). API-defined.', max_length=50)),
                ('file_url', models.URLField(help_text='URL of the file in storage (e.g. MinIO bucket)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(help_text='Resource (folder) this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='community_resource.resource')),
            ],
            options={
                'verbose_name': 'Resource Content',
                'verbose_name_plural': 'Resource Contents',
                'db_table': 'ResourceContent',
                'ordering': ['-created_at'],
            },
        ),
    ]
