# Generated by Django 6.0.1 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecontent',
            name='title',
            field=models.CharField(default='', help_text='Title of this content (file)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcecontent',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this content', null=True),
        ),
    ]
