# Generated by Django 6.0.1 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_resource', '0002_resourcecontent_title_and_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecontent',
            name='content_source',
            field=models.CharField(
                blank=True,
                help_text='Source of the content, e.g. upload, youtube, vimeo (API-defined string)',
                max_length=50,
                null=True,
            ),
        ),
    ]
