# Generated by Django 6.0.1 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_resource', '0003_resourcecontent_content_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Whether this resource is active and visible. Inactive resources can be hidden from members.',
            ),
        ),
        migrations.AddField(
            model_name='resourcecontent',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Whether this content is active and visible. Inactive content can be hidden from members.',
            ),
        ),
    ]
