# Generated by Django 6.0.1 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_resource', '0004_resource_and_resourcecontent_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecontent',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='resourcecontent',
            name='resource_type',
            field=models.CharField(
                blank=True,
                help_text='Type/category of resource content (API-defined string)',
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='resourcecontent',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL of the thumbnail image for this content', null=True),
        ),
        migrations.AlterModelOptions(
            name='resourcecontent',
            options={
                'ordering': ['order', '-created_at'],
                'verbose_name': 'Resource Content',
                'verbose_name_plural': 'Resource Contents',
                'db_table': 'ResourceContent',
            },
        ),
    ]
