# Generated by Django 6.0.1 on 2026-04-29 12:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_event', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communityevent',
            new_name='CommunityEv_communi_bd9b69_idx',
            old_name='CommunityEv_communi_b6c73a_idx',
        ),
        migrations.RenameIndex(
            model_name='communityevent',
            new_name='CommunityEv_communi_79b180_idx',
            old_name='CommunityEv_communi_80f0ee_idx',
        ),
        migrations.RenameIndex(
            model_name='communityeventprice',
            new_name='CommunityEv_communi_93c471_idx',
            old_name='CommunityEv_communi_bb9207_idx',
        ),
        migrations.RenameIndex(
            model_name='eventregistration',
            new_name='EventRegist_event_i_5b8faf_idx',
            old_name='EventRegist_event_i_b7ac98_idx',
        ),
        migrations.RenameIndex(
            model_name='eventregistration',
            new_name='EventRegist_attende_14d2d7_idx',
            old_name='EventRegist_attende_bda489_idx',
        ),
        migrations.RenameIndex(
            model_name='eventregistration',
            new_name='EventRegist_stripe__a4fb35_idx',
            old_name='EventRegist_stripe__70337d_idx',
        ),
        migrations.RenameIndex(
            model_name='eventregistration',
            new_name='EventRegist_paystac_329f3d_idx',
            old_name='EventRegist_paystac_82e095_idx',
        ),
        migrations.RenameIndex(
            model_name='eventregistration',
            new_name='EventRegist_payment_d8f8e0_idx',
            old_name='EventRegist_payment_67ff2d_idx',
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy list price; prefer CommunityEventPrice rows per currency', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='communityeventprice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
