# Generated by Django 6.0.1 on 2026-04-30 22:14

import app_models.community_event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_event', '0005_eventregistration_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityevent',
            name='agenda',
            field=models.JSONField(blank=True, default=app_models.community_event.models._default_agenda, help_text='Ordered schedule segments as JSON list, e.g. [{"title": str, "description": optional, "starts_at": iso-8601, "ends_at": iso-8601}]'),
        ),
    ]
