# Generated by Django 6.0.1 on 2026-03-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_store', '0002_storepurchase_stripe_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storedownloadtoken',
            new_name='StoreDownlo_expires_36e863_idx',
            old_name='StoreDownloadToken_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='storeproduct',
            new_name='StoreProduc_store_i_c9c95a_idx',
            old_name='StoreProduct_store_id_2a8f91_idx',
        ),
        migrations.RenameIndex(
            model_name='storepurchase',
            new_name='StorePurcha_product_6f2fcf_idx',
            old_name='StorePurchase_product_0f3c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='storepurchase',
            new_name='StorePurcha_status_ad4ad0_idx',
            old_name='StorePurchase_status_8b1d4e_idx',
        ),
        migrations.RenameIndex(
            model_name='storepurchase',
            new_name='StorePurcha_stripe__e34692_idx',
            old_name='StorePurchase_stripe_pi_idx',
        ),
        migrations.RenameIndex(
            model_name='storepurchase',
            new_name='StorePurcha_stripe__affee0_idx',
            old_name='StorePurchase_stripe_cs_idx',
        ),
    ]
