# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_store', '0003_rename_storedownloadtoken_expires_idx_storedownlo_expires_36e863_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepurchase',
            name='billing_country',
            field=models.CharField(
                blank=True,
                help_text='ISO 3166-1 alpha-2 country for this checkout',
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='storepurchase',
            name='payment_gateway',
            field=models.CharField(
                blank=True,
                choices=[('stripe', 'Stripe'), ('paystack', 'Paystack')],
                help_text='Payment processor handling this purchase',
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='storepurchase',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storepurchase',
            name='paystack_subscription_code',
            field=models.CharField(
                blank=True,
                help_text='Set when purchase uses a Paystack subscription; usually null for one-off store sales',
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='storepurchase',
            name='paystack_transaction_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='storepurchase',
            index=models.Index(fields=['paystack_transaction_reference'], name='StorePurchase_paystack_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='storepurchase',
            index=models.Index(fields=['payment_gateway'], name='StorePurchase_gateway_idx'),
        ),
    ]
