# Generated by Django 6.0.1 on 2026-03-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_store', '0004_storepurchase_billing_gateway_paystack'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storepurchase',
            new_name='StorePurcha_paystac_185d60_idx',
            old_name='StorePurchase_paystack_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='storepurchase',
            new_name='StorePurcha_payment_b760ee_idx',
            old_name='StorePurchase_gateway_idx',
        ),
    ]
