# Generated by Django 6.0.1 on 2026-04-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_store', '0006_store_product_kinds_prices_booking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storeowneravailabilitywindow',
            new_name='StoreOwnerA_setting_53b679_idx',
            old_name='StoreOwnerA_setting_idx',
        ),
        migrations.RenameIndex(
            model_name='storeproduct',
            new_name='StoreProduc_store_i_fac342_idx',
            old_name='StoreProduct_store_pr_idx',
        ),
        migrations.RenameIndex(
            model_name='storeproductprice',
            new_name='StoreProduc_store_p_44ef72_idx',
            old_name='StoreProduc_store_pr_idx',
        ),
        migrations.RenameIndex(
            model_name='storeproductslothold',
            new_name='StoreProduc_store_p_4720d8_idx',
            old_name='StoreProduc_store_pr_0f1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='storepurchase',
            new_name='StorePurcha_booked__ff00d9_idx',
            old_name='StorePurcha_booked__idx',
        ),
    ]
