# Generated by Django 6.0.1 on 2026-04-27 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_meetings', '0004_rename_payment_plans_m2m_to_community_groups'),
        ('community_store', '0008_remove_storeproduct_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproduct',
            name='template_meeting',
            field=models.ForeignKey(blank=True, help_text='Legacy/admin: fixed meeting row; bookable products use bookable_meeting_settings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_products_ticket', to='community_meetings.meeting'),
        ),
    ]
