# Generated by Django 6.0.1 on 2026-09-27 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_meetings', '0005_meeting_room_source'),
        ('community_store', '0012_store_meeting_sessions_conference'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storeguestemailchallenge',
            new_name='StoreGuestE_email_d45c55_idx',
            old_name='StoreGuestE_email_ex_idx',
        ),
        migrations.RenameIndex(
            model_name='storepurchase',
            new_name='StorePurcha_slot_se_faf25f_idx',
            old_name='StorePurcha_slot_se_idx',
        ),
        migrations.RenameIndex(
            model_name='storepurchase',
            new_name='StorePurcha_checkou_dea36f_idx',
            old_name='StorePurcha_checkou_idx',
        ),
        migrations.RenameIndex(
            model_name='storeslotsession',
            new_name='StoreSlotSe_store_p_00d40a_idx',
            old_name='StoreSlotSe_store_p_idx',
        ),
        migrations.RenameIndex(
            model_name='storeslotsession',
            new_name='StoreSlotSe_confere_8f7796_idx',
            old_name='StoreSlotSe_confere_idx',
        ),
        migrations.AlterField(
            model_name='storepurchase',
            name='booked_meeting',
            field=models.ForeignKey(blank=True, help_text='Legacy: meeting created or linked after payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_purchases', to='community_meetings.meeting'),
        ),
    ]
