# Generated by Django 6.0.1 on 2026-01-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Feed message content')),
                ('allow_replies', models.BooleanField(default=True, help_text='If true, users can reply to this feed. If false, replies are disabled.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(help_text='Community that owns this feed item', on_delete=django.db.models.deletion.CASCADE, related_name='public_feeds', to='community.community')),
                ('parent_feed', models.ForeignKey(blank=True, help_text='Parent feed if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community_publicfeeds.publicfeed')),
                ('posted_by', models.ForeignKey(help_text='Community member who posted this on behalf of the community', on_delete=django.db.models.deletion.CASCADE, related_name='public_feed_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Public Feed',
                'verbose_name_plural': 'Public Feeds',
                'db_table': 'PublicFeeds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicFeedsAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(help_text='URL of the attached file')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], help_text='Type of attachment (image or video)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('public_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='community_publicfeeds.publicfeed')),
            ],
            options={
                'verbose_name': 'Public Feeds Attachment',
                'verbose_name_plural': 'Public Feeds Attachments',
                'db_table': 'PublicFeedsAttachment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicFeedsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('public_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community_publicfeeds.publicfeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_feed_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Public Feeds Like',
                'verbose_name_plural': 'Public Feeds Likes',
                'db_table': 'PublicFeedsLike',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'public_feed')},
            },
        ),
    ]
