# Generated by Django 6.0.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_line1', models.CharField(blank=True, default='', help_text='Street address, line 1', max_length=255)),
                ('street_line2', models.CharField(blank=True, help_text='Street address, line 2 (optional)', max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, help_text='Country name for display (e.g. on invoices)', max_length=255, null=True)),
                ('billing_country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2; set for billing addresses for Paystack/Stripe routing', max_length=2, null=True)),
                ('billing_region', models.CharField(blank=True, help_text='State/province or subdivision for tax and payment routing (e.g. code or name as required by the gateway)', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='Optional app-specific use (not the same as billing_region unless you choose to mirror it)', max_length=100, null=True)),
                ('is_billing_address', models.BooleanField(default=False, help_text='True if this address is used for billing/invoicing')),
                ('is_default_billing', models.BooleanField(default=False, help_text='True if this is the default billing address among billing rows')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User address',
                'verbose_name_plural': 'User addresses',
                'db_table': 'UserAddress',
                'ordering': ['-is_default_billing', '-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'is_billing_address'], name='UserAddress_user_bill_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'is_default_billing'], name='UserAddress_user_def_idx'),
        ),
        migrations.AddConstraint(
            model_name='useraddress',
            constraint=models.UniqueConstraint(
                condition=Q(is_default_billing=True),
                fields=('user',),
                name='useraddress_unique_default_billing_per_user',
            ),
        ),
    ]
