# Generated by Django 6.0.1 on 2026-03-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_useraddress'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useraddress',
            new_name='UserAddress_user_id_9fdbb6_idx',
            old_name='UserAddress_user_bill_idx',
        ),
        migrations.RenameIndex(
            model_name='useraddress',
            new_name='UserAddress_user_id_212b34_idx',
            old_name='UserAddress_user_def_idx',
        ),
    ]
