# Generated by Django — replace billing booleans with address_type

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def forwards_assign_address_type(apps, schema_editor):
    UserAddress = apps.get_model('user_profile', 'UserAddress')
    UserAddress.objects.filter(
        Q(is_billing_address=True) | Q(is_default_billing=True),
    ).update(address_type='billing')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofilesociallink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(
                default='residence',
                help_text='Purpose of this address (e.g. billing, tax, residence); values are defined by your API/product',
                max_length=64,
            ),
        ),
        migrations.RunPython(forwards_assign_address_type, noop_reverse),
        migrations.RemoveConstraint(
            model_name='useraddress',
            name='useraddress_unique_default_billing_per_user',
        ),
        migrations.RemoveIndex(
            model_name='useraddress',
            name='UserAddress_user_id_9fdbb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='useraddress',
            name='UserAddress_user_id_212b34_idx',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='is_billing_address',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='is_default_billing',
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'address_type'], name='UserAddress_user_id_type_idx'),
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={
                'ordering': ['address_type', '-updated_at'],
                'verbose_name': 'User address',
                'verbose_name_plural': 'User addresses',
            },
        ),
    ]
