# Generated by Django 6.0.1 on 2026-01-28 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the forum (e.g., "General", "Announcements")', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the forum', null=True)),
                ('restrict_posting_to_owners_moderators', models.BooleanField(default=False, help_text='If true, only owners and moderators can post on this forum. If false, all members can post.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='community.community')),
                ('payment_plans', models.ManyToManyField(blank=True, help_text='Payment plans that have access to this forum', related_name='forums', to='community.paymentplan')),
            ],
            options={
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Forums',
                'db_table': 'Forum',
                'ordering': ['created_at'],
                'unique_together': {('community', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Post message content')),
                ('allow_replies', models.BooleanField(default=True, help_text='If true, users can reply to this post. If false, replies are disabled.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community_forum.forum')),
                ('parent_post', models.ForeignKey(blank=True, help_text='Parent post if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community_forum.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'Post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(help_text='URL of the attached file')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], help_text='Type of attachment (image or video)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='community_forum.post')),
            ],
            options={
                'verbose_name': 'Post Attachment',
                'verbose_name_plural': 'Post Attachments',
                'db_table': 'PostAttachment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community_forum.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Like',
                'verbose_name_plural': 'Post Likes',
                'db_table': 'PostLike',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
