# Generated by Django 6.0.1 on 2026-01-28 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community_classroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the classroom content', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the classroom content', null=True)),
                ('notes', models.TextField(blank=True, help_text='Classroom content notes/details', null=True)),
                ('content_url', models.URLField(blank=True, help_text='URL of the classroom content (video, document, etc.)', null=True)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('article', 'Article'), ('link', 'Link'), ('other', 'Other')], default='other', help_text='Type of content (video, document, article, link, other)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this content is active and visible to members. Owners and moderators can see inactive content.')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first). Used for drag-and-drop reordering by owners/moderators.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(help_text='Classroom this content belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='community_classroom.classroom')),
            ],
            options={
                'verbose_name': 'Classroom Content',
                'verbose_name_plural': 'Classroom Contents',
                'db_table': 'ClassroomContent',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(help_text='URL of the attached file')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('file', 'File')], help_text='Type of attachment (image, video, pdf, or file)', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Description of the attachment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(help_text='Classroom content this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='community_classroom_content.classroomcontent')),
            ],
            options={
                'verbose_name': 'Classroom Attachment',
                'verbose_name_plural': 'Classroom Attachments',
                'db_table': 'ClassroomAttachment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_url', models.URLField(blank=True, help_text='URL of the certificate file (if stored)', null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True, help_text='When the certificate was issued')),
                ('classroom', models.ForeignKey(help_text='Classroom this certificate is for', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='community_classroom.classroom')),
                ('user', models.ForeignKey(help_text='User who received the certificate', on_delete=django.db.models.deletion.CASCADE, related_name='classroom_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classroom Certificate',
                'verbose_name_plural': 'Classroom Certificates',
                'db_table': 'ClassroomCertificate',
                'ordering': ['-issued_at'],
                'unique_together': {('classroom', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ClassroomContentCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, help_text='When the content was marked as complete')),
                ('content', models.ForeignKey(help_text='Content that was completed', on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='community_classroom_content.classroomcontent')),
                ('user', models.ForeignKey(help_text='User who completed the content', on_delete=django.db.models.deletion.CASCADE, related_name='classroom_content_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classroom Content Completion',
                'verbose_name_plural': 'Classroom Content Completions',
                'db_table': 'ClassroomContentCompletion',
                'ordering': ['-completed_at'],
                'unique_together': {('content', 'user')},
            },
        ),
    ]
