# Generated by Django 6.0.1 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_classroom_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomcontent',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL of the thumbnail image for this content', null=True),
        ),
    ]
