# Generated by Django 6.0.1 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_classroom_content', '0002_classroomcontent_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomcontent',
            name='content_type',
        ),
        migrations.AddField(
            model_name='classroomcontent',
            name='content_source',
            field=models.CharField(
                blank=True,
                help_text='Source of the video, e.g. upload, youtube, vimeo, twitter (API-defined string)',
                max_length=50,
                null=True,
            ),
        ),
    ]
