# Generated by Django 6.0.1 on 2026-02-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_classroom_content', '0003_replace_content_type_with_content_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomcontent',
            name='content_url',
            field=models.URLField(blank=True, help_text='URL of the classroom content (video)', null=True),
        ),
    ]
