# Generated by Django 6.0.1 on 2026-05-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_classroom_content', '0006_classroomresource'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='classroomresource',
            new_name='ClassroomRe_content_78118c_idx',
            old_name='ClassroomReso_content_91e711_idx',
        ),
        migrations.RenameIndex(
            model_name='classroomresource',
            new_name='ClassroomRe_classro_3b2bca_idx',
            old_name='ClassroomReso_classro_4f8b22_idx',
        ),
    ]
