# Generated by Django 6.0.1 on 2026-05-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_classroom', '0007_classroom_is_featured'),
        ('community_classroom_content', '0008_lesson_definitions_and_remove_legacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroomlessonplacement',
            options={'ordering': ['order', '-id'], 'verbose_name': 'Classroom Lesson Placement', 'verbose_name_plural': 'Classroom Lesson Placements'},
        ),
        migrations.AlterModelOptions(
            name='lessondefinition',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lesson Definition', 'verbose_name_plural': 'Lesson Definitions'},
        ),
        migrations.AlterModelOptions(
            name='lessondefinitionattachment',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Lesson Definition Attachment', 'verbose_name_plural': 'Lesson Definition Attachments'},
        ),
        migrations.AlterModelOptions(
            name='lessonplacementcompletion',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Lesson Placement Completion', 'verbose_name_plural': 'Lesson Placement Completions'},
        ),
        migrations.AlterField(
            model_name='lessondefinition',
            name='content_source',
            field=models.CharField(blank=True, help_text='Source: application, youtube, vimeo, etc.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lessondefinition',
            name='content_url',
            field=models.URLField(blank=True, help_text='URL of main content (video) or MinIO object path', null=True),
        ),
        migrations.AlterField(
            model_name='lessondefinition',
            name='description',
            field=models.TextField(blank=True, help_text='Description', null=True),
        ),
        migrations.AlterField(
            model_name='lessondefinition',
            name='notes',
            field=models.TextField(blank=True, help_text='Lesson notes/details', null=True),
        ),
        migrations.AlterField(
            model_name='lessondefinition',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Thumbnail image URL (public)', null=True),
        ),
        migrations.AlterField(
            model_name='lessondefinitionattachment',
            name='content_source',
            field=models.CharField(blank=True, help_text='For video: youtube, vimeo, etc.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lessondefinitionattachment',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description (legacy attachments)', null=True),
        ),
        migrations.AlterField(
            model_name='lessondefinitionattachment',
            name='kind',
            field=models.CharField(choices=[('link', 'Link'), ('file', 'File'), ('video', 'Video'), ('supplement', 'Supplement')], help_text='link, file (stored path), video (URL), supplement (legacy attachment)', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessondefinitionattachment',
            name='supplement_file_type',
            field=models.CharField(blank=True, help_text='When kind=supplement: image, video, pdf, file', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lessondefinitionattachment',
            name='url',
            field=models.TextField(blank=True, help_text='External URL or MinIO object path', null=True),
        ),
        migrations.AddIndex(
            model_name='classroomlessonplacement',
            index=models.Index(fields=['classroom'], name='ClassroomLe_classro_739b78_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomlessonplacement',
            index=models.Index(fields=['lesson_definition'], name='ClassroomLe_lesson__60fc72_idx'),
        ),
        migrations.AddIndex(
            model_name='lessondefinitionattachment',
            index=models.Index(fields=['lesson_definition'], name='LessonDefin_lesson__c6f307_idx'),
        ),
    ]
