# Generated by Django 6.0.1 on 2026-08-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_classroom_content', '0011_classroomlessonplacement_is_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessondefinition',
            name='bunny_video_id',
            field=models.CharField(blank=True, help_text='Bunny Stream video GUID', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='lessondefinition',
            name='video_status',
            field=models.CharField(choices=[('none', 'None'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', help_text='Adaptive HLS state (Bunny Stream or legacy MinIO video bucket)', max_length=20),
        ),
    ]
