# Generated by Django 6.0.1 on 2026-04-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_telegram', '0005_split_platform_private_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitytelegram',
            name='platform_chat_id',
            field=models.CharField(blank=True, help_text='Chat/channel id when using the platform bot (TELEGRAM_BOT_TOKEN); set by platform link or PATCH.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='communitytelegram',
            name='private_bot_chat_id',
            field=models.CharField(blank=True, help_text='Chat/channel id when using this community’s private BotFather token.', max_length=64, null=True),
        ),
    ]
