# Generated by Django 6.0.1 on 2026-05-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_journey', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='learningjourney',
            new_name='LearningJou_communi_96deef_idx',
            old_name='LearningJourney_community_idx',
        ),
        migrations.RenameIndex(
            model_name='learningjourney',
            new_name='LearningJou_communi_e22264_idx',
            old_name='LearningJourney_communi_e85470_idx',
        ),
        migrations.RenameIndex(
            model_name='learningjourneyedge',
            new_name='LearningJou_journey_f97d76_idx',
            old_name='LearningJourneyEdge_journey_idx',
        ),
        migrations.RenameIndex(
            model_name='learningjourneyedge',
            new_name='LearningJou_from_no_fa0b71_idx',
            old_name='LearningJourneyEdge_from_node_idx',
        ),
        migrations.RenameIndex(
            model_name='learningjourneyedge',
            new_name='LearningJou_to_node_3e5def_idx',
            old_name='LearningJourneyEdge_to_node_idx',
        ),
        migrations.RenameIndex(
            model_name='learningjourneyenrollment',
            new_name='LearningJou_journey_92f99e_idx',
            old_name='LearningJourneyEnrollment_journey_idx',
        ),
        migrations.RenameIndex(
            model_name='learningjourneyenrollment',
            new_name='LearningJou_communi_f5bad0_idx',
            old_name='LearningJourneyEnrollment_member_idx',
        ),
        migrations.RenameIndex(
            model_name='learningjourneynode',
            new_name='LearningJou_journey_72615c_idx',
            old_name='LearningJourneyNode_journey_idx',
        ),
    ]
