# Generated by Django 6.0.1 on 2026-09-28 20:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_course', '0011_rename_classroom_to_course'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coursebundle',
            new_name='CourseBundl_communi_736e61_idx',
            old_name='ClassroomCo_communi_13e0d2_idx',
        ),
        migrations.AlterField(
            model_name='course',
            name='banner_url',
            field=models.URLField(blank=True, help_text='URL of the course banner image', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the course', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='If True, the course may be highlighted in discovery; at most six per community may be featured.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False, help_text='If True, the course is visible/published to members'),
        ),
        migrations.AlterField(
            model_name='course',
            name='issue_certificate',
            field=models.BooleanField(default=False, help_text='If True, users will receive a certificate when all content in the course is completed'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Name of the course. Only letters, numbers, hyphens (-) and underscores (_) allowed.', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_slug_username', message='May only contain letters, numbers, hyphens (-) and underscores (_).', regex='^[a-zA-Z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Set once when the course is first published; remains set if is_published is toggled off so downstream notifications fire only once.', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Title of the course', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursebundle',
            name='banner_url',
            field=models.URLField(blank=True, help_text='Optional bundle-only banner URL (not derived from courses)', null=True),
        ),
        migrations.AlterField(
            model_name='coursebundle',
            name='title',
            field=models.CharField(help_text='Display title of the bundle', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursebundleitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Sort order within the bundle (lower first)'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(help_text='Course this review is for', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='community_course.course'),
        ),
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
        migrations.AlterModelTable(
            name='coursebundle',
            table='CourseBundle',
        ),
        migrations.AlterModelTable(
            name='coursebundleitem',
            table='CourseBundleItem',
        ),
        migrations.AlterModelTable(
            name='coursereview',
            table='CourseReview',
        ),
    ]
