# Generated by Django 6.0.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityLeaveReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField(help_text='Reason for leaving the community')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(help_text='Community the user left', on_delete=django.db.models.deletion.CASCADE, related_name='leave_reasons', to='community.community')),
                ('user', models.ForeignKey(blank=True, help_text='User who left (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_leave_reasons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Leave Reason',
                'verbose_name_plural': 'Community Leave Reasons',
                'db_table': 'CommunityLeaveReason',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['community'], name='CommLeaveRe_communi_idx'),
                    models.Index(fields=['created_at'], name='CommLeaveRe_created_idx'),
                ],
            },
        ),
    ]
