# Generated by Django 6.0.1 on 2026-02-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_leave_reason', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communityleavereason',
            new_name='CommunityLe_communi_00190d_idx',
            old_name='CommLeaveRe_communi_idx',
        ),
        migrations.RenameIndex(
            model_name='communityleavereason',
            new_name='CommunityLe_created_158434_idx',
            old_name='CommLeaveRe_created_idx',
        ),
    ]
