# Generated by Django 6.0.1 on 2026-01-28 18:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0001_initial"),
        ("auth", "0001_initial"),
    ]
    run_before = [
        ("admin", "0001_initial"),  # Admin's migration references User table
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'UserRole',
                'verbose_name_plural': 'UserRoles',
                'db_table': 'UserRole',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, db_index=True, help_text='Only letters, numbers, hyphens (-) and underscores (_) allowed.', max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug_username', message='May only contain letters, numbers, hyphens (-) and underscores (_).', regex='^[a-zA-Z0-9_-]+$')])),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('verification_token', models.CharField(blank=True, max_length=64, null=True)),
                ('reset_password_token', models.CharField(blank=True, max_length=64, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('pending_email', models.EmailField(blank=True, help_text='New email address pending verification', max_length=254, null=True)),
                ('email_change_code', models.CharField(blank=True, help_text='6-digit verification code for email change', max_length=6, null=True)),
                ('email_change_code_expires_at', models.DateTimeField(blank=True, help_text='Expiration time for email change code', null=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='account.userrole')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
            },
        ),
    ]
