# Generated by Django 6.0.1 on 2026-01-28 18:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the classroom. Only letters, numbers, hyphens (-) and underscores (_) allowed.', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_slug_username', message='May only contain letters, numbers, hyphens (-) and underscores (_).', regex='^[a-zA-Z0-9_-]+$')])),
                ('title', models.CharField(help_text='Title of the classroom', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the classroom', null=True)),
                ('banner_url', models.URLField(blank=True, help_text='URL of the classroom banner image', null=True)),
                ('enforce_progression', models.BooleanField(default=False, help_text='If True, users must complete content in order (one at a time). Owners/moderators can view all content regardless.')),
                ('issue_certificate', models.BooleanField(default=False, help_text='If True, users will receive a certificate when all content in the classroom is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='community.community')),
                ('payment_plans', models.ManyToManyField(blank=True, help_text='Payment plans that have access to this classroom', related_name='classrooms', to='community.paymentplan')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'db_table': 'Classroom',
                'ordering': ['-created_at'],
                'unique_together': {('community', 'name')},
            },
        ),
    ]
