# Generated by Django 5.2.1 on 2026-05-03 15:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_classroom', '0005_rename_payment_plans_m2m_to_community_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Star rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('message', models.TextField(blank=True, help_text='Optional review message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(help_text='Classroom this review is for', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='community_classroom.classroom')),
                ('user', models.ForeignKey(help_text='User who left the review', on_delete=django.db.models.deletion.CASCADE, related_name='classroom_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classroom Review',
                'verbose_name_plural': 'Classroom Reviews',
                'db_table': 'ClassroomReview',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['classroom'], name='ClassroomRe_classro_d01c7a_idx'), models.Index(fields=['user', 'classroom'], name='ClassroomRe_user_id_b4e024_idx')],
                'unique_together': {('user', 'classroom')},
            },
        ),
    ]
