# Generated by Django 6.0.1 on 2026-05-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_classroom', '0006_classroom_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='If True, the classroom may be highlighted in discovery; at most six per community may be featured.'),
        ),
    ]
