# Generated by Django 6.0.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_classroom', '0007_classroom_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display title of the collection', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('banner_url', models.URLField(blank=True, help_text='Optional collection-only banner URL (not derived from classrooms)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(help_text='Community this collection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='classroom_collections', to='community.community')),
            ],
            options={
                'verbose_name': 'Classroom Collection',
                'verbose_name_plural': 'Classroom Collections',
                'db_table': 'ClassroomCollection',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order within the collection (lower first)')),
                ('classroom', models.ForeignKey(help_text='Classroom placed in the collection', on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='community_classroom.classroom')),
                ('collection', models.ForeignKey(help_text='Collection this row belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='community_classroom.classroomcollection')),
            ],
            options={
                'verbose_name': 'Classroom Collection Item',
                'verbose_name_plural': 'Classroom Collection Items',
                'db_table': 'ClassroomCollectionItem',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='classroomcollectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'classroom'), name='uniq_classroomcollectionitem_collection_classroom'),
        ),
        migrations.AddIndex(
            model_name='classroomcollection',
            index=models.Index(fields=['community'], name='ClassroomCo_communi_7e8b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomcollectionitem',
            index=models.Index(fields=['collection', 'order'], name='ClassroomCo_collect_8a1c4f_idx'),
        ),
    ]
