# Generated by Django 6.0.1 on 2026-05-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_classroom', '0008_classroom_collection'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='classroomcollection',
            new_name='ClassroomCo_communi_13e0d2_idx',
            old_name='ClassroomCo_communi_7e8b2e_idx',
        ),
        migrations.RenameIndex(
            model_name='classroomcollectionitem',
            new_name='ClassroomCo_collect_0cf7dd_idx',
            old_name='ClassroomCo_collect_8a1c4f_idx',
        ),
    ]
