# Generated by Django 6.0.1 on 2026-09-28 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0030_community_bunny_collection_id'),
        ('community_course', '0012_rename_classroomco_communi_13e0d2_idx_coursebundl_communi_736e61_idx_and_more'),
        ('member_engagement', '0002_rename_classroom_to_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='engagementsession',
            name='engsess_comm_cl_last_idx',
        ),
        migrations.AddIndex(
            model_name='engagementsession',
            index=models.Index(fields=['community', 'course', '-last_seen_at'], name='engsess_comm_cl_last_idx'),
        ),
    ]
