# Generated by Django 6.0.1 on 2026-01-28 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(choices=[('free_hobby', 'Free/Hobby (Starter)'), ('hobby', 'Hobby (Growing)'), ('professional', 'Professional (Established)'), ('enterprise', 'Enterprise (Scale)')], help_text='Tier identifier', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Display name for the tier', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Monthly price', max_digits=10)),
                ('max_communities', models.IntegerField(blank=True, help_text='Maximum number of communities (null = unlimited)', null=True)),
                ('max_members', models.IntegerField(blank=True, help_text='Maximum members per community (null = unlimited)', null=True)),
                ('max_admins', models.IntegerField(blank=True, help_text='Maximum admins (co-owners + moderators) per community (null = unlimited)', null=True)),
                ('max_free_payment_plans', models.IntegerField(blank=True, help_text='Maximum free payment plans per community (null = unlimited)', null=True)),
                ('max_paid_payment_plans', models.IntegerField(blank=True, help_text='Maximum paid payment plans per community (null = unlimited)', null=True)),
                ('max_quiz_generations_per_month', models.IntegerField(blank=True, help_text='Maximum quiz generations per month (null = unlimited)', null=True)),
                ('max_forums', models.IntegerField(blank=True, help_text='Maximum forums per community (null = unlimited)', null=True)),
                ('max_classrooms', models.IntegerField(blank=True, help_text='Maximum classrooms per community (null = unlimited)', null=True)),
                ('storage_limit_gb', models.IntegerField(blank=True, help_text='Storage limit in GB per owner (null = unlimited)', null=True)),
                ('has_basic_analytics', models.BooleanField(default=False)),
                ('has_advanced_analytics', models.BooleanField(default=False)),
                ('has_custom_reports', models.BooleanField(default=False)),
                ('has_standard_support', models.BooleanField(default=False)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('has_24_7_support', models.BooleanField(default=False)),
                ('has_custom_branding', models.BooleanField(default=False)),
                ('has_white_label', models.BooleanField(default=False)),
                ('has_meeting_features', models.BooleanField(default=False)),
                ('has_advanced_meeting_features', models.BooleanField(default=False)),
                ('has_export_data', models.BooleanField(default=False)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_custom_integrations', models.BooleanField(default=False)),
                ('has_revenue_analytics', models.BooleanField(default=False)),
                ('has_dedicated_manager', models.BooleanField(default=False)),
                ('has_custom_development', models.BooleanField(default=False)),
                ('has_sso_saml', models.BooleanField(default=False)),
                ('has_advanced_security', models.BooleanField(default=False)),
                ('has_custom_sla', models.BooleanField(default=False)),
                ('has_multi_community_dashboard', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Subscription Tier',
                'verbose_name_plural': 'App Subscription Tiers',
                'db_table': 'AppSubscriptionTier',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='AppSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Community owner', on_delete=django.db.models.deletion.CASCADE, related_name='app_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(help_text='Subscription tier', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='app_subscription.appsubscriptiontier')),
            ],
            options={
                'verbose_name': 'App Subscription',
                'verbose_name_plural': 'App Subscriptions',
                'db_table': 'AppSubscription',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMemberSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', help_text='Current status of the subscription', max_length=20)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='When the subscription was created')),
                ('activated_at', models.DateTimeField(blank=True, help_text='When the subscription was activated (payment confirmed)', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the subscription expires (for recurring plans)', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the subscription was cancelled', null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe subscription ID (for recurring subscriptions)', max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe customer ID', max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe payment intent ID (for one-time payments)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(help_text='Community this subscription is for', on_delete=django.db.models.deletion.CASCADE, related_name='member_subscriptions', to='community.community')),
                ('payment_plan', models.ForeignKey(help_text='Payment plan user is subscribed to', on_delete=django.db.models.deletion.CASCADE, related_name='member_subscriptions', to='community.paymentplan')),
                ('user', models.ForeignKey(help_text='Member who has the subscription', on_delete=django.db.models.deletion.CASCADE, related_name='community_member_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Member Subscription',
                'verbose_name_plural': 'Community Member Subscriptions',
                'db_table': 'CommunityMemberSubscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('app_subscription', 'App Subscription'), ('community_member_subscription', 'Community Member Subscription')], help_text='Type of transaction', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total payment amount (100% of fee)', max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, help_text='Platform fee (2% for community subscriptions, 0 for app subscriptions)', max_digits=10)),
                ('owner_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount to owner (98% for community subscriptions, 0 for app subscriptions)', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code (USD, EUR, etc.)', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Payment status', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(help_text='Stripe payment intent ID', max_length=255, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, help_text='Stripe charge ID', max_length=255, null=True)),
                ('transferred_to_owner', models.BooleanField(default=False, help_text='Whether the owner amount has been transferred to the community owner')),
                ('transferred_at', models.DateTimeField(blank=True, help_text='When the transfer to owner was completed', null=True)),
                ('stripe_transfer_id', models.CharField(blank=True, help_text='Stripe transfer ID (if using Stripe Connect)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the payment was completed', null=True)),
                ('app_subscription', models.ForeignKey(blank=True, help_text='App subscription (if transaction_type is app_subscription)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app_subscription.appsubscription')),
                ('community_member_subscription', models.ForeignKey(blank=True, help_text='Community member subscription (if transaction_type is community_member_subscription)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app_subscription.communitymembersubscription')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'PaymentTransaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='MinIO object path', max_length=500)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(choices=[('avatar', 'Avatar'), ('banner', 'Banner'), ('classroom_content', 'Classroom Content'), ('classroom_attachment', 'Classroom Attachment'), ('forum_attachment', 'Forum Attachment'), ('post_attachment', 'Post Attachment'), ('quiz_file', 'Quiz File'), ('blog_image', 'Blog Image'), ('featured_content', 'Featured Content'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(blank=True, help_text='Community this file belongs to (null for user profile files)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_usage', to='community.community')),
                ('owner', models.ForeignKey(help_text='Community owner (for per-owner storage limits)', on_delete=django.db.models.deletion.CASCADE, related_name='storage_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Storage Usage',
                'verbose_name_plural': 'Storage Usage',
                'db_table': 'StorageUsage',
            },
        ),
        migrations.AddIndex(
            model_name='appsubscription',
            index=models.Index(fields=['user', 'status'], name='AppSubscrip_user_id_9dfe72_idx'),
        ),
        migrations.AddIndex(
            model_name='appsubscription',
            index=models.Index(fields=['status', 'expires_at'], name='AppSubscrip_status_d4758e_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembersubscription',
            index=models.Index(fields=['user', 'community', 'status'], name='CommunityMe_user_id_646221_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembersubscription',
            index=models.Index(fields=['status', 'expires_at'], name='CommunityMe_status_2b3260_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitymembersubscription',
            unique_together={('user', 'community')},
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['app_subscription', 'status'], name='PaymentTran_app_sub_777437_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['community_member_subscription', 'status'], name='PaymentTran_communi_914bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['stripe_payment_intent_id'], name='PaymentTran_stripe__805ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transferred_to_owner'], name='PaymentTran_transfe_353555_idx'),
        ),
        migrations.AddIndex(
            model_name='storageusage',
            index=models.Index(fields=['owner'], name='StorageUsag_owner_i_4df10b_idx'),
        ),
        migrations.AddIndex(
            model_name='storageusage',
            index=models.Index(fields=['community', 'owner'], name='StorageUsag_communi_9dd573_idx'),
        ),
        migrations.AddIndex(
            model_name='storageusage',
            index=models.Index(fields=['file_path'], name='StorageUsag_file_pa_500c5d_idx'),
        ),
    ]
