# Generated by Django 6.0.1 on 2026-03-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0005_paymenttransaction_store_purchase'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='PaymentTran_store_p_60c6da_idx',
            old_name='PaymentTran_store_p_idx',
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='owner_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount owed to the community owner after platform_fee (e.g. 98% for member subs and store sales)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform cut (e.g. 2% for community subscriptions and store sales; 0 for app subscriptions)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, help_text='Stripe Transfer id (Connect) or payout reference for owner_amount', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total payment amount charged to the buyer', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('app_subscription', 'App Subscription'), ('community_member_subscription', 'Community Member Subscription'), ('store_purchase', 'Store Product Purchase')], help_text='Type of transaction', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transferred_to_owner',
            field=models.BooleanField(default=False, help_text='Whether owner_amount has been paid out to the community owner'),
        ),
    ]
