# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0006_rename_paymenttran_store_p_idx_paymenttran_store_p_60c6da_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsubscription',
            name='billing_country',
            field=models.CharField(
                blank=True,
                help_text='ISO 3166-1 alpha-2 country used for this subscription checkout',
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='appsubscription',
            name='payment_gateway',
            field=models.CharField(
                blank=True,
                choices=[('stripe', 'Stripe'), ('paystack', 'Paystack')],
                help_text='Payment processor handling this subscription',
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='appsubscription',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appsubscription',
            name='paystack_subscription_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appsubscription',
            name='paystack_transaction_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communitymembersubscription',
            name='billing_country',
            field=models.CharField(
                blank=True,
                help_text='ISO 3166-1 alpha-2 country for this member subscription checkout',
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='communitymembersubscription',
            name='payment_gateway',
            field=models.CharField(
                blank=True,
                choices=[('stripe', 'Stripe'), ('paystack', 'Paystack')],
                help_text='Payment processor handling this subscription',
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='communitymembersubscription',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communitymembersubscription',
            name='paystack_subscription_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communitymembersubscription',
            name='paystack_transaction_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='billing_country',
            field=models.CharField(
                blank=True,
                help_text='ISO 3166-1 alpha-2 country for this charge',
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_gateway',
            field=models.CharField(
                blank=True,
                choices=[('stripe', 'Stripe'), ('paystack', 'Paystack')],
                help_text='Processor that captured this payment',
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='paystack_transaction_reference',
            field=models.CharField(
                blank=True,
                help_text='Paystack transaction reference (null when payment_gateway is stripe)',
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='paystack_transfer_reference',
            field=models.CharField(
                blank=True,
                help_text='Paystack transfer reference when owner_amount is paid out via Paystack',
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='stripe_payment_intent_id',
            field=models.CharField(
                blank=True,
                help_text='Stripe PaymentIntent id (null when payment_gateway is paystack)',
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_gateway'], name='PaymentTran_gateway_idx'),
        ),
    ]
