# Generated by Django 6.0.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0007_billing_gateway_paystack_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorPayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_gateway', models.CharField(choices=[('stripe', 'Stripe'), ('paystack', 'Paystack')], help_text='Processor this payout account is registered with', max_length=20)),
                ('label', models.CharField(blank=True, default='', help_text='Optional label shown to the creator (e.g. main bank, NGN wallet)', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending onboarding'), ('active', 'Active — payouts enabled'), ('restricted', 'Restricted'), ('disabled', 'Disabled')], default='pending', help_text='Onboarding / capability state mirrored from the gateway where possible', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Preferred account for this user on this gateway (splits / transfers)')),
                ('stripe_connect_account_id', models.CharField(blank=True, help_text='Stripe Connect account id (acct_…)', max_length=255, null=True)),
                ('paystack_subaccount_code', models.CharField(blank=True, help_text='Paystack subaccount code for split settlements', max_length=255, null=True)),
                ('paystack_recipient_code', models.CharField(blank=True, help_text='Paystack transfer recipient code for payouts to bank/mobile money', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Creator (community owner) receiving payouts', on_delete=django.db.models.deletion.CASCADE, related_name='creator_payout_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creator payout account',
                'verbose_name_plural': 'Creator payout accounts',
                'db_table': 'CreatorPayoutAccount',
                'ordering': ['-is_primary', '-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='creatorpayoutaccount',
            index=models.Index(fields=['user', 'payment_gateway', 'status'], name='CreatorPay_user_gate_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorpayoutaccount',
            index=models.Index(fields=['user', 'is_primary'], name='CreatorPay_user_primary_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorpayoutaccount',
            index=models.Index(fields=['stripe_connect_account_id'], name='CreatorPay_stripe_acct_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorpayoutaccount',
            index=models.Index(fields=['paystack_subaccount_code'], name='CreatorPay_paystack_sub_idx'),
        ),
        migrations.AddConstraint(
            model_name='creatorpayoutaccount',
            constraint=models.UniqueConstraint(
                condition=Q(is_primary=True),
                fields=('user', 'payment_gateway'),
                name='creatorpayoutaccount_unique_primary_per_user_gateway',
            ),
        ),
    ]
