# Generated by Django 6.0.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0008_creatorpayoutaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='creator_payout_account',
            field=models.ForeignKey(
                blank=True,
                help_text='Creator payout profile used when transferring owner_amount (audit trail)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='payment_transactions',
                to='app_subscription.creatorpayoutaccount',
            ),
        ),
    ]
