# Generated by Django 6.0.1 on 2026-03-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0009_paymenttransaction_creator_payout_account'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='creatorpayoutaccount',
            new_name='CreatorPayo_user_id_cd8639_idx',
            old_name='CreatorPay_user_gate_stat_idx',
        ),
        migrations.RenameIndex(
            model_name='creatorpayoutaccount',
            new_name='CreatorPayo_user_id_a79758_idx',
            old_name='CreatorPay_user_primary_idx',
        ),
        migrations.RenameIndex(
            model_name='creatorpayoutaccount',
            new_name='CreatorPayo_stripe__1fe35b_idx',
            old_name='CreatorPay_stripe_acct_idx',
        ),
        migrations.RenameIndex(
            model_name='creatorpayoutaccount',
            new_name='CreatorPayo_paystac_90f293_idx',
            old_name='CreatorPay_paystack_sub_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='PaymentTran_payment_93971b_idx',
            old_name='PaymentTran_gateway_idx',
        ),
    ]
