# Generated by Django 6.0.1

import django.db.models.deletion
from django.db import migrations, models


def seed_usd_prices_from_legacy_price(apps, schema_editor):
    AppSubscriptionTier = apps.get_model('app_subscription', 'AppSubscriptionTier')
    AppSubscriptionTierPrice = apps.get_model('app_subscription', 'AppSubscriptionTierPrice')
    for tier in AppSubscriptionTier.objects.all():
        AppSubscriptionTierPrice.objects.update_or_create(
            tier=tier,
            currency='USD',
            defaults={'amount': tier.price},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0010_rename_creatorpay_user_gate_stat_idx_creatorpayo_user_id_cd8639_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSubscriptionTierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='ISO 4217 code (e.g. USD, NGN, GHS, ZAR)', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Price in major units of this currency', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(help_text='Subscription tier this price applies to', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='app_subscription.appsubscriptiontier')),
            ],
            options={
                'verbose_name': 'App subscription tier price',
                'verbose_name_plural': 'App subscription tier prices',
                'db_table': 'AppSubscriptionTierPrice',
            },
        ),
        migrations.AddConstraint(
            model_name='appsubscriptiontierprice',
            constraint=models.UniqueConstraint(fields=('tier', 'currency'), name='appsubtierprice_unique_tier_currency'),
        ),
        migrations.RunPython(seed_usd_prices_from_legacy_price, noop_reverse),
    ]
