# Generated by Django 6.0.1 on 2026-03-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0012_remove_moved_models_from_app_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsubscriptiontier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy monthly amount (kept in sync for admin UX); canonical per-currency amounts live on AppSubscriptionTierPrice', max_digits=10),
        ),
    ]
