# Generated by Django 6.0.1 on 2026-03-31 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0014_remove_appsubscriptiontier_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsubscriptiontier',
            options={'ordering': ['tier_name'], 'verbose_name': 'App Subscription Tier', 'verbose_name_plural': 'App Subscription Tiers'},
        ),
    ]
