# Generated by Django 5.x migration template

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0015_alter_appsubscriptiontier_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTierDiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Public code (match case-insensitively in application code)', max_length=64, unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='0–100: percent off list tier price (100 = free checkout)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('expires_at', models.DateTimeField(blank=True, help_text='When set, code is invalid at or after this instant (timezone-aware)', null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='When set, code cannot be redeemed more than this many times (successful payments only)', null=True)),
                ('redeemed_count', models.PositiveIntegerField(default=0, help_text='Number of successful redemptions (incremented by payment service)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(blank=True, help_text='When set, code only applies to this tier', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='app_subscription.appsubscriptiontier')),
            ],
            options={
                'verbose_name': 'App tier discount code',
                'verbose_name_plural': 'App tier discount codes',
                'db_table': 'AppTierDiscountCode',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppTierDiscountCodeAllowedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_normalized', models.CharField(db_index=True, help_text='Lowercased, trimmed email', max_length=254)),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_emails', to='app_subscription.apptierdiscountcode')),
            ],
            options={
                'verbose_name': 'App tier discount code allowed email',
                'verbose_name_plural': 'App tier discount code allowed emails',
                'db_table': 'AppTierDiscountCodeAllowedEmail',
            },
        ),
        migrations.AddConstraint(
            model_name='apptierdiscountcodeallowedemail',
            constraint=models.UniqueConstraint(fields=('discount_code', 'email_normalized'), name='apptierdiscountallowed_unique_code_email'),
        ),
        migrations.AddField(
            model_name='appsubscription',
            name='applied_discount_code',
            field=models.ForeignKey(blank=True, help_text='Discount code applied at subscribe (snapshot percent stored separately)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_subscriptions', to='app_subscription.apptierdiscountcode'),
        ),
        migrations.AddField(
            model_name='appsubscription',
            name='discount_percent_applied',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of discount_percent at checkout so code edits do not change in-flight amounts', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='appsubscription',
            name='discount_redeemed_at',
            field=models.DateTimeField(blank=True, help_text='When redemption was counted against the code (idempotency for confirm vs webhook)', null=True),
        ),
    ]
