# Generated by Django — AppSubscriptionTier: entitlements JSON replaces columnar limits/features

from django.db import migrations, models


def copy_columns_to_entitlements(apps, schema_editor):
    AppSubscriptionTier = apps.get_model("app_subscription", "AppSubscriptionTier")
    for tier in AppSubscriptionTier.objects.all():
        limits = {
            "max_communities": tier.max_communities,
            "max_members": tier.max_members,
            "max_admins": tier.max_admins,
            "max_free_community_groups": tier.max_free_community_groups,
            "max_paid_community_groups": tier.max_paid_community_groups,
            "max_quiz_generations_per_month": tier.max_quiz_generations_per_month,
            "max_forums": tier.max_forums,
            "max_classrooms": tier.max_classrooms,
            "max_resources": None,
            "storage_limit_gb": tier.storage_limit_gb,
        }
        features = {
            "has_store_access": False,
            "has_events_access": False,
            "has_blog_access": False,
            "has_api_access": bool(tier.has_api_access),
            "has_custom_domain": False,
            "has_custom_email": False,
        }
        tier.entitlements = {"limits": limits, "features": features}
        tier.save(update_fields=["entitlements"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("app_subscription", "0016_apptierdiscountcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsubscriptiontier",
            name="entitlements",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Caps and feature flags: {\"limits\": {...}, \"features\": {...}}. "
                    "Integer limits use null for unlimited. "
                    "max_admins counts co-owners and moderators only (owner excluded). "
                    "See app_models.app_subscription.entitlements."
                ),
            ),
        ),
        migrations.RunPython(copy_columns_to_entitlements, noop_reverse),
        migrations.RemoveField(model_name="appsubscriptiontier", name="max_communities"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="max_members"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="max_admins"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="max_free_community_groups"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="max_paid_community_groups"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="max_quiz_generations_per_month"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="max_forums"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="max_classrooms"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="storage_limit_gb"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_basic_analytics"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_advanced_analytics"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_custom_reports"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_standard_support"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_priority_support"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_24_7_support"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_custom_branding"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_white_label"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_meeting_features"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_advanced_meeting_features"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_export_data"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_api_access"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_custom_integrations"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_revenue_analytics"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_dedicated_manager"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_custom_development"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_sso_saml"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_advanced_security"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_custom_sla"),
        migrations.RemoveField(model_name="appsubscriptiontier", name="has_multi_community_dashboard"),
    ]
