# Generated by Django 6.0.1 on 2026-09-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_course_content', '0016_rename_classroom_to_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselessonplacement',
            name='is_preview',
            field=models.BooleanField(default=False, help_text='When true, unauthenticated visitors can view this syllabus row (notes and playback) on the public course page.'),
        ),
        migrations.AlterField(
            model_name='courselessonplacement',
            name='order',
            field=models.IntegerField(default=0, help_text='Order within this course (lower first)'),
        ),
        migrations.AlterModelTable(
            name='coursecertificate',
            table='CourseCertificate',
        ),
        migrations.AlterModelTable(
            name='courselessonplacement',
            table='CourseLessonPlacement',
        ),
    ]
