# Generated by Django 6.0.1 on 2026-01-28 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Meeting title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Meeting description/notes', null=True)),
                ('start_datetime', models.DateTimeField(help_text='Start date and time')),
                ('end_datetime', models.DateTimeField(help_text='End date and time')),
                ('location', models.CharField(blank=True, help_text='Physical meeting location', max_length=500, null=True)),
                ('meeting_url', models.URLField(blank=True, help_text='Virtual meeting URL (Zoom, Google Meet, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, help_text='Users invited to the meeting', related_name='meetings_attending', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='community.community')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('payment_plans', models.ManyToManyField(blank=True, help_text='Payment plans that have access to this meeting', related_name='meetings', to='community.paymentplan')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'db_table': 'Meeting',
                'ordering': ['start_datetime'],
            },
        ),
    ]
