# Generated by Django 6.0.1 on 2026-01-28 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the blog post', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (auto-generated from title)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description/summary of the blog post', null=True)),
                ('blog_message', models.TextField(help_text='Content of the blog post')),
                ('image_url', models.URLField(blank=True, help_text='URL of the blog post image', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('writer', models.ForeignKey(help_text='User who wrote this blog post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'BlogPost',
                'ordering': ['-created_at'],
            },
        ),
    ]
