# Generated by Django 6.0.1 on 2026-01-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique code/slug for this badge (e.g. signup, referral, early_adopter_1000)', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Display name of the badge', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Short description of how to earn this badge', null=True)),
                ('icon_url', models.URLField(blank=True, help_text='URL of the badge icon image (optional)', null=True)),
                ('criteria', models.JSONField(blank=True, default=dict, help_text='Optional criteria (e.g. {"max_rank": 1000} for early adopter)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Badge Definition',
                'verbose_name_plural': 'Badge Definitions',
                'db_table': 'BadgeDefinition',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(help_text='The badge that was awarded', on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='badges.badgedefinition')),
                ('user', models.ForeignKey(help_text='User who was awarded this badge', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='account.user')),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'db_table': 'UserBadge',
                'ordering': ['-awarded_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
